### PR TITLE
add created=true option if user specify volumeID

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/8628

**Comment by StrongMonkey** [comment]
We need to pass `created=true` to volume so that when it gets created, it can be deactivated by cattle and then turns to be in `detached` state. This prevents `no such volume` errors because storage driver looks only for `active` volume.

**Comment by cjellick** [comment]
Discussed with @StrongMonkey. Going to close this once he makes the appropriate change in cattle that would make this unneeded.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/cattle/pull/2673

**Pull request closed without merging**
