### PR TITLE
fix(rancher-ebs): Detach nvme EBS volume

### PR DESCRIPTION
**Pull request by snahelou**
Hello

The last fix for EBS with NVME is not complete. The mount function is ok but the unmount is not implemented :) 

The problem is disks are never unmounted, so they are never unmounted, so they are never deleted.

Regards
Sebastien

### CODE REVIEW

**Comment by snahelou** [comment]
Hello

No news ? 

Your EBS plugin is not working on AWS C5 instances.

BR

**Comment by snahelou** [comment]
Up?

**Comment by mikemoate** [comment]
@StrongMonkey @niusmallnan @deniseschannon how do we get this PR considered please (later PR's have been merged, this is a key piece of missing support for newer AWS instance types)?

**Comment by StrongMonkey** [comment]
@mikemoate we will look at it and possibly take it into our next release. In the mean time as a workaround, you can take this pr and build your own storage service based upon it.

**Pull request closed without merging**
