### PR TITLE
mount to _data subDir

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by cjellick** [comment]
rancher/rancher#8465

**Comment by cjellick** [comment]
The problem is that this won't work kubernetes and flexvols where the paradigm is flipped and we don't have control the path.

**Review by cjellick — CHANGES_REQUESTED** [review]
See my above general comment. Not going to work with k8s. @galal-hussein might be able to guide your through testing this on k8s

**Comment by StrongMonkey** [comment]
close in favor of https://github.com/rancher/storage/pull/52

**Pull request closed without merging**
