### PR TITLE
add snapshot, encryption and tags options to EBS volume creation

### PR DESCRIPTION
**Pull request by wonderslug**
The EBS volume creation did not have the snapshot-id and encryption options available to it.  I know we would like to use those options for our environment and i belive others will as well.

It adds the following options to the driver_options sections:

snapshotID
encryption ("true" enables it)
kmsKeyID (only looked for if encryption enabled)
tags

example usage: 
```
volumes:
  data:
    driver: rancher-ebs
    per_container: true
    driver_opts:
      name: test_data
      size: 10
      volumeType: gp2
      snapshotID: <some snapshot id>
      encryption: true
      kmsKeyID: <some keyid> 
      tags: "Key=Stack,Value=production Key=webserver,Value= "
```

### CODE REVIEW

**Review by lasley — APPROVED** [review]
Thanks 👍

**Comment by brettneese** [comment]
Definitely looking forward to seeing this merged ;-)

**Comment by smazurov** [comment]
What is holding this up, if anything? There is no BC breaks - it just improves already existing functionality.

**Comment by StrongMonkey** [comment]
LGTM on my side. Need @LLParse to review it.

**Comment by LLParse** [comment]
LGTM, thanks for this @wonderslug.

**Comment by wjimenez5271** [comment]
We need to make sure that the scheduler/docker will wait for the EBS volume to be created. In the case of a large snapshot (think 900GB or more), AWS can take some time to create a volume and for it to be ready for attachment. We need to make sure that the container isn't started until the EBS device is ready.

**Comment by LLParse** [comment]
@wjimenez5271 Did you mean to post this here? I don't see how it is relevant to the PR.

@cjellick Can you please merge this?

**Comment by wjimenez5271** [comment]
@LLParse Yes, I think so...should I have put this somewhere else?

**Comment by cjellick** [comment]
@StrongMonkey @LLParse @wjimenez5271 did any of your run this PR to validate it functions as expected?

**Comment by StrongMonkey** [comment]
@cjellick I run it before and it works

**Comment by cjellick** [comment]
@wjimenez5271 fyi, you put your comments in the correct place and I see your point. The scheduler will not be impacted by the amount of time it takes to create the volume. From the agent/docker perspective, we fortunately just switched to a no-timeout client for docker volume create to address a different issue, so we should be good on that front as well. Thanks for bringing it up.

**Comment by cjellick** [comment]
LGTM

**Comment by LLParse** [comment]
A little late to see this, but yes I tested the encryption options and they worked. I didn't notice or test the snapshot logic, hence my confusion regarding @wjimenez5271 comment. I think this PR existed without the snapshot option at some point.

**Pull request merged**
